[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
ffi = true
ast = true
build_info = true
# auto_detect_solc = true

[fuzz]
runs = 100

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"

[etherscan]
ethereum = { key = "${ETHEREUM_EXPLORER_API_KEY}", url = "https://api.etherscan.io/api" }
base_sepolia = { key = "${BASE_EXPLORER_API_KEY}", url = "https://api-sepolia.basescan.org/api" }


